### ISSUE TITLE
ap.olech2412.de not accessible

### ISSUE THREAD

**Issue by whosFritz** [olech2412/MensaHub-Gateway#23]
I get this Error:

Diese Seite funktioniert im Moment nicht. 
Wenn das Problem weiterhin besteht, wenden Sie sich an den Besitzer (du Ole lol) der Website.
HTTP ERROR 401

401 describes the "no authorization" error code

![image](https://github.com/olech2412/EssensGetter-API/assets/97552289/a812992b-75c4-4c91-b7b4-100ce7977dd5)

**Comment by olech2412** [comment]
Sehr geehrter Herr Schubert,

dabei handelt es sich nicht um einen Fehler sondern um ein Feature. Erstellen Sie sich einen Account unter egr,olech2412.de mit den ihnen zur Verfügung gestellten Login-Daten.

Mit freundlichen Grüßen,
Ole

**Comment by whosFritz** [comment]
Ich bin ein Vollidiot lol

**Comment by olech2412** [comment]
WTF? Was ist mit ihnen?

**Comment by whosFritz** [comment]
Could not navigate to 'dev'

**Comment by olech2412** [comment]
![image](https://github.com/olech2412/EssensGetter-API/assets/76694468/fb291eb5-3b94-4153-90db-4a05218cb4d6)

**Comment by whosFritz** [comment]
btw ich hab niemanden am telefon verstanden

**Comment by olech2412** [comment]
> ## Could not navigate to 'dev'
> http://api.olech2412.de/essensGetter/auth/Login Whitelabel Error Page This application has no explicit mapping for /error, so you are seeing this as a fallback.
> 
> Tue Jun 06 15:43:59 CEST 2023 There was an unexpected error (type=Not Found, status=404).

ERSTENS IST DAS FALSCH GESCHRIEBEN UND ZWEITENS MUSST DU DA NEN POST MACHEN

![image](https://github.com/olech2412/EssensGetter-API/assets/76694468/9bd9c553-71fa-426e-994f-8baad46fe7b6)

**Comment by whosFritz** [comment]
ICH HAB DEN LINK AUS DEINER WHATSAPP GENOMMEN

**Comment by olech2412** [comment]
> btw ich hab niemanden am telefon verstanden



> ERSTENS IST DAS FALSCH GESCHRIEBEN UND ZWEITENS MUSST DU DA NEN POST MACHEN



> ICH HAB DEN LINK AUS DEINER WHATSAPP GENOMMEN

MIT WELCHEM ACCOUNT HAST DU DICH ANGEMELDET?

**Comment by olech2412** [comment]
Zugang zur API persönlich abgesprochen - Issue wird geschlossen
